Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  #config.vm.box = "centos/7"

  config.vm.network "private_network", ip: "192.168.56.4"
  
  config.vm.network :forwarded_port, guest: 3000, host: 3000   #NODE
  config.vm.network :forwarded_port, guest: 9229, host: 9229   #NODE DEBUGGER
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 8081, host: 8081
  config.vm.network :forwarded_port, guest: 27017, host: 27017  #MONGO
  
  #config.ssh.forward_agent = true
  
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder "Courses/", "/Projetos"
  
  config.vm.provider "virtualbox" do |v|
	  v.name = "COURSES"
  
	  v.gui = false  
    v.memory = 4096
	
	  #Enable SymLink 
	  #v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
  end
  
  config.vm.provision :shell, path: "provision.sh"
  config.vm.provision :shell, path: "node.sh"
  #config.vm.provision :shell, path: "yarn.sh"
  #config.vm.provision :shell, path: "aws.sh"
  config.vm.provision :shell, path: "docker.sh"
  config.vm.provision :shell, path: "dcompose.sh"
  config.vm.provision :shell, path: "mongodb.sh"
end
